### ISSUE TITLE
using `psql` command in container

### ISSUE THREAD

**Issue by Aiden-Jeon** [mlops-for-mle/tutorial#29]
컨테이너에서 `psql` 을 이용하여 DB 에 접속할 수 있도록 `postgresql-client` 를 설치합니다.

**Comment by Haeun-Oh** [comment]
> **컨테이너**에서 `psql` 을 이용하여 DB 에 접속할 수 있도록 `postgresql-client` 를 설치합니다.

의 의미는 
**2.3 Data 확인** 의

> psql 을 이용하여 DB 에 접속하고, 계속해서 데이터가 삽입되고 있는지 확인해보겠습니다.

작업을 docker container안에서 실행하는 걸까요?

> docker run --name data-generator --network "my-network" data-generator "postgres-server"
위의 명령어를 실행시키면 
`print(insert_row_query)`가 계속 실행되 명령어를 입력할 수 없을 것으로 보이는데요

container가 아니라 desktop에서 실행하는 것일까요?
data-generator container안에서 psql 명령어를 시도하는 것인지 아니면 desktop에서 실행하는 것인지 명시해주시면 Data 확인 부분에 대한 이해가 좀 더 수월할 거 같습니다.

**Comment by Haeun-Oh** [comment]
다른 얘기이긴 한데 psql로 접속한 후 빠져나오고 싶을 때 `exit`을 해야하는데 이에 대한 설명이 **1) DB Server Creation** 부분부터 없는 거 같습니다. 
추가하면 좋을 거 같기도 하고 기본 상식이라서 안 넣으셨을 수도 있을 거 같아 한번 적어봅니다~

**Comment by dongminlee94** [comment]
@Aiden-Jeon @Haeun-Oh 이 issue 는 close 해도 될 것 같습니다~ 없으면 안되는 걸로 확인 완료했습니다~

**Comment by dongminlee94** [comment]
> 다른 얘기이긴 한데 psql로 접속한 후 빠져나오고 싶을 때 `exit`을 해야하는데 이에 대한 설명이 **1) DB Server Creation** 부분부터 없는 거 같습니다. 추가하면 좋을 거 같기도 하고 기본 상식이라서 안 넣으셨을 수도 있을 거 같아 한번 적어봅니다~

@Haeun-Oh 음.. 나름 알아서 빠져나올 것 같긴한데.. ㅋㅋ @Aiden-Jeon 종섭님 의견 궁금합니다 ㅋㅋ

**Comment by Kimdongui** [comment]
> 다른 얘기이긴 한데 psql로 접속한 후 빠져나오고 싶을 때 `exit`을 해야하는데 이에 대한 설명이 **1) DB Server Creation** 부분부터 없는 거 같습니다. 추가하면 좋을 거 같기도 하고 기본 상식이라서 안 넣으셨을 수도 있을 거 같아 한번 적어봅니다~

@dongminlee94 
저는 하은님 말대로 `01. Database` 에서는 있으면 좋겠다는 의견입니다. 아마 대부분은 빠져나올 수 있겠지만, 파트 자체가 데이터 베이스에 관한 내용을 다루니 명시적으로 `exit` 방법이 있는 것도 좋을 것 같습니다.

**Comment by Aiden-Jeon** [comment]
> @Aiden-Jeon @Haeun-Oh 이 issue 는 close 해도 될 것 같습니다~ 없으면 안되는 걸로 확인 완료했습니다~

넵~

**Comment by Aiden-Jeon** [comment]
> > 다른 얘기이긴 한데 psql로 접속한 후 빠져나오고 싶을 때 `exit`을 해야하는데 이에 대한 설명이 **1) DB Server Creation** 부분부터 없는 거 같습니다. 추가하면 좋을 거 같기도 하고 기본 상식이라서 안 넣으셨을 수도 있을 거 같아 한번 적어봅니다~
> 
> @dongminlee94 저는 하은님 말대로 `01. Database` 에서는 있으면 좋겠다는 의견입니다. 아마 대부분은 빠져나올 수 있겠지만, 파트 자체가 데이터 베이스에 관한 내용을 다루니 명시적으로 `exit` 방법이 있는 것도 좋을 것 같습니다.

보통 잘 안적지 않나요? ㅋㅋ 알아서 빠져나가서..

**Comment by Kimdongui** [comment]
오 그러면 적지않는 것으로 하시죠 ~!
